# Generated by Django 5.1.3 on 2024-12-01 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='staus',
            new_name='status',
        ),
    ]
